# Generated by Django 4.1 on 2022-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoies_data',
            name='montant_device',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='envoies_data',
            name='type_service',
            field=models.CharField(default='', max_length=100),
        ),
    ]
