# Generated by Django 4.1 on 2022-08-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0002_envoies_data_montant_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envoies_data',
            old_name='adresse_beneficiare',
            new_name='adresse_beneficiaire',
        ),
    ]
