# Generated by Django 4.1 on 2022-08-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0003_rename_adresse_beneficiare_envoies_data_adresse_beneficiaire'),
    ]

    operations = [
       
    ]
