# Generated by Django 4.1 on 2022-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0004_remove_envoies_data_montant_device_and_more'),
    ]

    operations = [
    ]
