# Generated by Django 4.1 on 2022-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0006_rename_montant_device_envoies_data_adresse_expediteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoies_data',
            name='frais_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='envoies_data',
            name='montant_beneficiaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='envoies_data',
            name='montant_envoie_sans_frais',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
