# Generated by Django 4.1 on 2022-09-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0008_alter_envoies_data_code_abonne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoies_data',
            name='montant_envoie_sans_frais',
        ),
    ]
