# Generated by Django 4.1 on 2022-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0009_remove_envoies_data_montant_envoie_sans_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoies_data',
            name='month_operation',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='envoies_data',
            name='year_operation',
            field=models.CharField(default='', max_length=5),
        ),
    ]
