# Generated by Django 4.1 on 2022-09-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0010_envoies_data_month_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoies_data',
            name='month_operation',
        ),
        migrations.RemoveField(
            model_name='envoies_data',
            name='year_operation',
        ),
        migrations.AddField(
            model_name='envoies_data',
            name='month_year_operation',
            field=models.CharField(default='', max_length=10),
        ),
    ]
