# Generated by Django 4.1 on 2022-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0011_remove_envoies_data_month_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoies_data',
            name='numero_transfer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
