# Generated by Django 4.1 on 2022-09-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0012_envoies_data_numero_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envoies_data',
            name='adresse_beneficiaire',
        ),
        migrations.RemoveField(
            model_name='envoies_data',
            name='numero_beneficiaire',
        ),
    ]
