# Generated by Django 4.1 on 2022-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobobsapi', '0015_envoies_data_email_expediteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envoies_data',
            name='data_operation',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='envoies_data',
            name='date_heure_operation',
            field=models.DateTimeField(default=''),
        ),
    ]
